ViewModels/AccNo/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP6.ViewModels.AccNo
{
    public class AddViewModel
    {
        public string Accno { get; set; }
        public string Accname { get; set; }
        public string Acctype { get; set; }
        public string Midtype { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
        public IList<AccNoList> accNoList { get; set; }
    }
}

ViewModels/AccNo/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP6.ViewModels.AccNo
{
    public class EditViewModel
    {
        public string Accno { get; set; }
        public string Accname { get; set; }
        public string Acctype { get; set; }
        public string Midtype { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
        public IList<AccNoList> accNoList { get; set; }
    }
}

ViewModels/AccNo/ExportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP6.ViewModels.AccNo
{
    public class ExportViewModel
    {
        public string StartAccno { get; set; }
        public string EndAccno { get; set; }
    }
}

ViewModels/AccNo/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP6.ViewModels.AccNo
{
    public class IndexViewModel
    {
        public string Accno { get; set; }
        public string Accname { get; set; }
        public string Acctype { get; set; }
        public string Midtype { get; set; }
        public bool IsSearch { get; set; }
        public IList<AccNoList> accNoList { get; set; }
    }

    public class AccNoList
    {
        public string Accno { get; set; }
        public string Accname { get; set; }
        public string Acctype { get; set; }
        public string Midtype { get; set; }
    }
}

ViewModels/Bank/AddViewModel.cs
using System.Collections.Generic;

namespace ERP6.ViewModels.Bank
{
    public class AddViewModel
    {
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public double Initamount { get; set; }
        public string Accno { get; set; }
        public string Initdate { get; set; }
        public string Ntus { get; set; }
        public List<Bank10List> bank10List { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

ViewModels/Bank/EditViewModel.cs
using System.Collections.Generic;

namespace ERP6.ViewModels.Bank
{
    public class EditViewModel
    {
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public double Initamount { get; set; }
        public string Accno { get; set; }
        public string Initdate { get; set; }
        public string Ntus { get; set; }
        public List<Bank10List> bank10List { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

ViewModels/Bou/AddViewModel.cs
using System.Collections.Generic;
using X.PagedList;

namespace ERP6.ViewModels.Bou
{
    public class AddViewModel
    {
        public string QuNo { get; set; }
        public string QuDate { get; set; }
        public string CoNo { get; set; }
        public string Corp { get; set; }
        public string Fax { get; set; }
        public string Atte { get; set; }
        public string Tel { get; set; }
        public string SendAddr { get; set; }
        public string Payment { get; set; }
        public string SendDate { get; set; }
        public string Memo { get; set; }
        public string Sales { get; set; }
        public string Ntus { get; set; }
        public double? Total { get; set; }
        public string Userid { get; set; }
        public string PaperTail { get; set; }
        public double? Total1 { get; set; }
        public double? Total0 { get; set; }
        public string YnPass { get; set; }
        public List<Bou10List> bou10List { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

ViewModels/Bou/EditViewModel.cs
using System.Collections.Generic;
using X.PagedList;

namespace ERP6.ViewModels.Bou
{
    public class EditViewModel
    {
        public string QuNo { get; set; }
        public string QuDate { get; set; }
        public string CoNo { get; set; }
        public string Corp { get; set; }
        public string Fax { get; set; }
        public string Atte { get; set; }
        public string Tel { get; set; }
        public string SendAddr { get; set; }
        public string Payment { get; set; }
        public string SendDate { get; set; }
        public string Memo { get; set; }
        public string Sales { get; set; }
        public string Ntus { get; set; }
        public double? Total { get; set; }
        public string Userid { get; set; }
        public string PaperTail { get; set; }
        public double? Total1 { get; set; }
        public double? Total0 { get; set; }
        public string YnPass { get; set; }
        public List<Bou10List> bou10List { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

ViewModels/In/AddViewModel.cs
using System.Collections.Generic;
using X.PagedList;

namespace ERP6.ViewModels.In
{
    public class AddViewModel
    {
        public string InNo { get; set; }
        public string InDate { get; set; }
        public string VendorNo { get; set; }
        public string Memo { get; set; }
        public string Ntus { get; set; }
        public double? Total1 { get; set; }
        public string Userid { get; set; }
        public string Paymonth { get; set; }
        public string StockPass { get; set; }
        public string YnClose { get; set; }
        public string InvoiceNo { get; set; }
        public string InType { get; set; }
        public double? Total { get; set; }
        public double? YesGet { get; set; }
        public double? CashDis { get; set; }
        public double? SubTot { get; set; }
        public double? NotGet { get; set; }
        public double? Total0 { get; set; }
        public double? Discount { get; set; }
        public List<In10List> in10List { get; set; }
        public List<In20List> in20List { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

ViewModels/In/EditViewModel.cs
using System.Collections.Generic;
using X.PagedList;

namespace ERP6.ViewModels.In
{
    public class EditViewModel
    {
        public string InNo { get; set; }
        public string InDate { get; set; }
        public string VendorNo { get; set; }
        public string Memo { get; set; }
        public string Ntus { get; set; }
        public double? Total1 { get; set; }
        public string Userid { get; set; }
        public string Paymonth { get; set; }
        public string StockPass { get; set; }
        public string YnClose { get; set; }
        public string InvoiceNo { get; set; }
        public string InType { get; set; }
        public double? Total { get; set; }
        public double? YesGet { get; set; }
        public double? CashDis { get; set; }
        public double? SubTot { get; set; }
        public double? NotGet { get; set; }
        public double? Total0 { get; set; }
        public double? Discount { get; set; }
        public List<In10List> in10List { get; set; }
        public List<In20List> in20List { get; set; }
        public bool IsSearch { get; set; }
        public bool IsTrue { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Controllers/AccNoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ERP6.Models;
using X.PagedList;
using ERP6.ViewModels.Vendor;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using System.IO;
using ERP6.ViewModels.AccNo;

namespace ERP6.Controllers
{
    public class AccNoController : Controller
    {
        private readonly EEPEF01Context _context;

        public AccNoController(EEPEF01Context context)
        {
            _context = context;
        }

        /// <summary>
        /// 首頁
        /// </summary>
        /// <param name="vm">IndexViewModel</param>
        /// <returns></returns>
        public async Task<IActionResult> Index(IndexViewModel vm)
        {
            try
            {
                if (!vm.IsSearch)
                {
                    //如果vendorNo有資料的話，帶出來
                    if (!string.IsNullOrEmpty(vm.Accno))
                    {
                        var accNoData = _context.Accno10.Where(x => x.Accno == vm.Accno).FirstOrDefault();

                        if (accNoData != null)
                        {
                            vm = new IndexViewModel
                            {
                                Accno = accNoData.Accno,
                                Accname = accNoData.Accname,
                                Acctype = accNoData.Acctype,
                                Midtype = accNoData.Midtype,
                            };
                        }
                    }
                }

                //取得會計科目代號檔資料
                var accNoList = await _context.Accno10.Select(x => new AccNoList
                {
                    Accno = x.Accno,
                    Accname = x.Accname,
                    Acctype = x.Acctype,
                    Midtype = x.Midtype,
                }).ToListAsync();

                //搜尋條件
                if (vm.IsSearch)
                {
                    //會計科目
                    if (!string.IsNullOrEmpty(vm.Accno))
                    {
                        accNoList = await accNoList.Where(x => x.Accno.Contains(vm.Accno)).ToListAsync();
                    }

                    //科目名稱
                    if (!string.IsNullOrEmpty(vm.Accname))
                    {
                        accNoList = await accNoList.Where(x => x.Accname.Contains(vm.Accname)).ToListAsync();
                    }

                    //會計大類
                    if (!string.IsNullOrEmpty(vm.Acctype))
                    {
                        accNoList = await accNoList.Where(x => x.Acctype.Contains(vm.Acctype)).ToListAsync();
                    }

                    //會計中類
                    if (!string.IsNullOrEmpty(vm.Midtype))
                    {
                        accNoList = await accNoList.Where(x => x.Midtype.Contains(vm.Midtype)).ToListAsync();
                    }
                }

                vm.accNoList = accNoList;

                return View(vm);
            }
            catch (Exception e)
            {
                throw;
            }
        }

        /// <summary>
        /// 新增資料
        /// </summary>
        /// <param name="AccNo">會計代碼編號</param>
        /// <returns></returns>
        public async Task<IActionResult> Add(string AccNo)
        {
            try
            {
                AddViewModel vm = new AddViewModel();

                //取得預設資料
                if (!string.IsNullOrEmpty(AccNo))
                {
                    var accNoData = await _context.Accno10.Where(x => x.Accno == AccNo).FirstOrDefaultAsync();

                    vm.Accname = accNoData.Accname;
                    vm.Acctype = accNoData.Acctype;
                    vm.Midtype = accNoData.Midtype;
                }


                //取得清單資料
                var accNoList = await _context.Accno10.Select(x => new AccNoList
                {
                    Accno = x.Accno,
                    Accname = x.Accname,
                    Acctype = x.Acctype,
                    Midtype = x.Midtype,
                }).ToListAsync();

                vm.accNoList = accNoList;

                return View(vm);
            }
            catch (Exception e)
            {
                throw;
            }
        }

        /// <summary>
        /// 新增資料
        /// </summary>
        /// <param name="vm">AddViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddViewModel vm)
        {
            try
            {
                //檢查accNo是否唯一
                var checkAccNo = _context.Accno10.Where(x => x.Accno == vm.Accno).FirstOrDefault();

                if (checkAccNo != null)
                {
                    vm.IsTrue = false;
                    vm.ErrorMessage = "會計代碼已經存在";

                    return Json(vm);
                }

                //新增所需資料(廠商)
                Accno10 insertData = new Accno10
                {
                    Accno = vm.Accno,
                    Accname = vm.Accname,
                    Acctype = vm.Acctype,
                    Midtype = vm.Midtype,
                };

                _context.Accno10.Add(insertData);
                await _context.SaveChangesAsync();

                vm.IsTrue = true;

                return Json(vm);
            }
            catch (Exception e)
            {
                throw;
            }
        }

        /// <summary>
        /// 編輯資料
        /// </summary>
        /// <param name="AccNo">會計科目代碼</param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(string AccNo)
        {
            EditViewModel vm = new EditViewModel();

            try
            {
                if (string.IsNullOrEmpty(AccNo))
                {
                    return NotFound();
                }

                //資料
                var AccNoData = _context.Accno10
                    .Where(x => x.Accno == AccNo).FirstOrDefault();

                if (AccNoData == null)
                {
                    return NotFound();
                }

                vm.Accno = AccNoData.Accno;
                vm.Accname = AccNoData.Accname;
                vm.Acctype = AccNoData.Acctype;
                vm.Midtype = AccNoData.Midtype;

                //廠商清單資料
                var accNoList = await _context.Accno10.Select(x => new AccNoList
                {
                    Accno = x.Accno,
                    Accname = x.Accname,
                    Acctype = x.Acctype,
                    Midtype = x.Midtype,
                }).ToListAsync();

                if (accNoList != null)
                {
                    vm.accNoList = accNoList;

                    return View(vm);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception e)
            {
                throw;
            }

        }

        /// <summary>
        /// 編輯資料
        /// </summary>
        /// <param name="vm">EditViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditViewModel vm)
        {
            try
            {
                vm.IsTrue = false;

                if (vm != null)
                {
                    Accno10 updateData = new Accno10
                    {
                        Accno = vm.Accno,
                        Accname = vm.Accname,
                        Acctype = vm.Acctype,
                        Midtype = vm.Midtype,
                    };

                    _context.Accno10.Update(updateData);
                    await _context.SaveChangesAsync();

                    vm.IsTrue = true;
                }
                else
                {
                    vm.IsTrue = false;
                    vm.ErrorMessage = "編輯失敗!";

                    return Json(vm);
                }

                return Json(vm);
            }
            catch (Exception)
            {

                throw;
            }
        }

        /// <summary>
        /// 刪除資料
        /// </summary>
        /// <param name="AccNo">會計科目代碼</param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(string AccNo)
        {
            try
            {
                if (string.IsNullOrEmpty(AccNo))
                {
                    return NotFound();
                }

                var deleteData = await _context.Accno10
                    .Where(x => x.Accno == AccNo).FirstOrDefaultAsync();

                if (deleteData != null)
                {
                    _context.Accno10.Remove(deleteData);
                    await _context.SaveChangesAsync();
                }

                return Json(true);
            }
            catch (Exception e)
            {

                throw;
            }
        }

        /// <summary>
        /// 匯出資料
        /// </summary>
        /// <param name="vendorNo"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Export(string StartVendorNo, string EndVendorNo, string VendorType)
        {
            #region SelectList

            //會計科目清單資料
            var accNoList = from accno10 in _context.Accno10
                            select new
                            {
                                Accno = accno10.Accno,
                                Accname = accno10.Accno + string.Empty + accno10.Accname
                            };

            //廠商清單
            ViewBag.AccNoList = new SelectList(accNoList.ToList(), "Accno", "Accname", string.Empty);

            #endregion

            ExportViewModel vm = new ExportViewModel();

            return View(vm);
        }

        /// <summary>

Views/AccNo/Add.cshtml
@model ERP6.ViewModels.AccNo.AddViewModel

@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/Layout.cshtml";
    string UserAc = HttpContextAccessor.HttpContext.Session.GetString("UserAc");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>弘隆食品有限公司</title>
    <link href="image/favico.ico" rel="shortcut icon">
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="~/js/jquery-2.1.4.min.js"></script>
    <style>
        .data-item.active {
            background-color: #F5F9FF;
        }
    </style>
</head>
<body>
    <article id="wrap">
        <!-- header -->
        <header class="header-wrap">
            <figure class="logo-wrap"><a href="@Url.Action("Index", "Home",new { UserAC = UserAc})"></a></figure>
            <div class="nav-wrap">
                <ul class="nav-list">
                    <li class="nav-item nav-1" title="進銷存系統">
                        <a href="@Url.Action("Index", "Vendor")"></a>
                    </li>
                    <li class="nav-item nav-2" title="財務系統">
                        <a href="###"></a>
                    </li>
                    <li class="nav-item nav-3  is-active" title="會計系統">
                        <a href="@Url.Action("Index", "AccNo")"></a>
                    </li>
                    <li class="nav-item nav-4" title="人事">
                        <a href="###"></a>
                    </li>
                    <li class="nav-item nav-5" title="代號系統">
                        <a href="###"></a>
                    </li>
                    <li class="nav-item nav-6" title="分析系統">
                        <a href="###"></a>
                    </li>
                    <li class="nav-item nav-7" title="安全系統">
                        <a href="###"></a>
                    </li>
                    <li class="nav-item nav-8" title="">
                        <a href="###"></a>
                    </li>
                </ul>
            </div>
            <div class="header-right">
                <!-- add system -->
                @*<div class="header-btn-add">
                        <a href="">
                            <i></i><span>新增系統</span>
                        </a>
                    </div>*@
                <!-- user info -->
                <div class="user-info">
                    <span>帳號名稱</span>
                    <h2>@UserAc</h2>
                </div>
                <!-- sign out -->
                <button class="signout-btn" onClick='window.location.href = "@Url.Action("Index", "Login")"'></button>
            </div>
        </header>
        <!-- main -->
        <main class="container-wrap">
            <!-- aside -->
            <aside class="aside-wrap">
                <div class="aside-head">ACC會計系統</div>
                <div class="aside-list">
                    <div class="aside-item">
                        <div class="aside-title is-c201 is-active">
                            <h2>會計系統</h2>
                        </div>
                        <div class="aside-link" style="display: block;">
                            <ul>
                                <li class="is-active">
                                    <a href="@Url.Action("Index", "AccNo")">C001_會計科目代號檔</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Customer")">C202_客戶基本資料檔</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Stock")">C203_產品基本資料檔</a>
                                </li>
                                <li>
                                    <a href="">C204_採購單資料建檔</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </aside>
            <!-- inner -->
            <div class="container-inner">
                <!-- top -->
                <div class="top-wrap">
                    <!-- top-title -->
                    <div class="top-title">
                        <h2>C001_會計科目代號檔</h2>
                    </div>
                    <!-- top-toollist -->
                    <div class="top-toollist">
                        <ul>
                            <li>
                                <button class="tool-btn-leave"><span>離開</span></button>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- content -->
                <div class="container-content">
                    <div class="container-column">
                        <div class="container-col-1">
                            <div class="data-wrap">
                                <div class="data-title">
                                    <div class="f-1 ta-left">會計科目</div>
                                    <div class="f-1 ta-left">科目名稱</div>
                                </div>
                                <div class="data-list">
                                    <!-- example start -->
                                    @foreach (var item in Model.accNoList)
                                    {
                                        <div class="data-item">
                                            <div class="f-1 accno ta-left">@item.Accno</div>
                                            <div class="f-1 ta-left">@item.Accname</div>
                                        </div>
                                    }
                                    <!-- example end -->
                                </div>
                            </div>
                        </div>
                        <div class="container-col-2">
                            <form id="form" method="post">
                                <div class="inside-wrap">
                                    <div class="inside-overflow">
                                        <div class="form-wrap">
                                            <div class="form-group">
                                                <div class="form-row">
                                                    <div class="form-flex f-1">
                                                        <div class="form-input">
                                                            <label for="">會計科目</label>
                                                            @Html.TextBoxFor(x => x.Accno)
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-row">
                                                    <div class="form-flex f-1">
                                                        <div class="form-input">
                                                            <label for="">科目名稱</label>
                                                            @Html.TextBoxFor(x => x.Accname)
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-row">
                                                    <div class="form-flex f-1">
                                                        <div class="form-input">
                                                            <label for="">會計大類</label>
                                                            @Html.TextBoxFor(x => x.Acctype)
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-row">
                                                    <div class="form-flex f-1">
                                                        <div class="form-input">
                                                            <label for="">會計中類</label>
                                                            @Html.TextBoxFor(x => x.Midtype)
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="btn-bottom">
                                            <button type="button" class="btn-clean search">清除條件</button>
                                            <button type="button" id="btnSubmit" class="btn-submit">確定</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- popup -->
        <!-- 確認視窗 -->
        <div class="popup-wrap check">
            <div class="p-form">
                <p>是否確定執行?</p>
                <div class="p-btn pad-0">
                    <button class="btn-cancel small check">取消</button>
                    <button type="button" id="btnCheck" class="btn-submit small check">確定</button>
                </div>
            </div>
        </div>
        <!-- overlay -->
        <div class="popup-overlay"></div>
    </article>
    <!-- JS -->
    <script src="~/js/script.js"></script>
    <script>

        //初始資料
        $(function () {
            //先清除所有資料的綁定狀態
            $('.data-item').each(function (i, v) {
                $(this).removeClass('active');
            });

            $("#Accno").val('');
        });

        //新增資料
        $(function () {
            $('#btnSubmit').on('click', function () {
                $(".popup-wrap.check").addClass("is-active");
                $(".popup-overlay").addClass("is-active");

                //取消
                $('.btn-cancel.small.check').on('click', function () {

                    $(".popup-wrap.check").removeClass("is-active");
                    $(".popup-overlay").removeClass("is-active");

                    window.location.href = "@Url.Action("Index", "AccNo")";
                });

                //確定
                $('.btn-submit.small.check').on('click', function () {
                    $(".popup-wrap.check").removeClass("is-active");
                    $(".popup-overlay").removeClass("is-active");

                    let fromData = $("#form").serialize();

                    $.ajax({
                        url: "@Url.Action("Add", "AccNo")",
                        data: fromData,
                        type: 'POST',
                        success: function (data) {
                            if (data.isTrue) {
                                alert("新增成功");

                                let accNo = data.accno;

                                window.location.href = "@Url.Action("Index", "AccNo")/?AccNo=" + accNo;
                            }
                            else {
                                alert(data.errorMessage);
                            }
                        }
                    });

                    $(".popup-wrap.check").removeClass("is-active");
                    $(".popup-overlay").removeClass("is-active")
                });
            });
        });

        //清除搜尋資料
        $('.btn-clean.search').on('click', function () {

            //清除資料
            $("#Accno").val('');
            $("#Accname").val('');
            $("#Acctype").val('');
            $("#Midtype").val('');
        });

        //離開
        $(function () {
            $(".tool-btn-leave").on('click', function () {
                window.location.href = "@Url.Action("Index","AccNo")";
            });
        });
    </script>
</body>
</html>